# This environment file contains environment values for shell support scripts.
#
# Example values
# CONTAINER_TOOL=podman
# CONTAINER_IMAGE_NAME=ub_pic32mx_dev
# REMOTE_REGISTRY="<registry_url>:5000/"
# FOLDER="ub_pic32mx_dev/"
# MAJOR_VER=0
# MINOR_VER=$MAJOR_VER.1

CONTAINER_TOOL=podman
CONTAINER_IMAGE_NAME=ub_pic32mx_dev
REMOTE_REGISTRY=""
FOLDER="ubuntu_dev/"
MAJOR_VER=0
MINOR_VER=1
BUILD_VER=1
MAJ_MIN_VER=$MAJOR_VER.$MINOR_VER
D_VERSION=$MAJOR_VER.$MINOR_VER.$BUILD_VER

# User
USER_NAME=developer
USER_ID=1000
GROUP_ID=1000

WORKDIR=/workdir

# Build ARG vars
MPLABX_VERSION=6.20
XC_TOOLCHAIN=xc32
XC_TOOLCHAIN_VERSION=4.45
ATPACK_NAME=PIC32MZ-EF_DFP
ATPACK_VERSION=1.4.168
SIM_ATPACK_NAME=Simulator_TP
SIM_ATPACK_VERSION=1.7.660
CURIOSITY_ATPACK_NAME=PKOB4_TP
CURIOSITY_ATPACK_VERSION=1.14.1168
